### ISSUE TITLE
License of this codes

### ISSUE THREAD

**Issue by Dictor** [yuecideng/RadialBasisFunctionCpp#1]
Hello, 

Thanks for your great effort of this repository.
I want to partially modify and re-use this for my code.
However I can't find license definition of this repository.

Would you like to notice license of this code?

Thanks.

**Comment by yuecideng** [comment]
Hi @Dictor , thanks for your interest. Is MIT suitable? I will add license later

**Comment by Dictor** [comment]
Appreciate for fast response, @yuecideng

That sounds very good for me.
I'll use as MIT license, thanks for allowrance.
